version: '3.8'
services:
  api:
    build: ./api
    container_name: api_container
    ports:
      - '5000:5000'
    volumes:
      - ./api:/app
      - /app/node_modules
  client:
    build: ./myblog
    container_name: react-app_container
    ports:
      - '3000:3000'
    volumes: # might not work on windows
      - ./myblog:/app
      - /app/node_modules
    stdin_open: true
    tty: true
